<?php

return [
    'admins' => [
        'name' => 'admins',
        'comment' => null,
        'label' => 'Admin',
        'columns' => [
            'id' => [
                'name' => 'id',
                'type_name' => 'integer',
                'type' => 'integer',
                'collation' => null,
                'nullable' => false,
                'default' => null,
                'auto_increment' => true,
                'comment' => null,
                'generation' => null,
                'label' => 'Id',
            ],
            'username' => [
                'name' => 'username',
                'type_name' => 'varchar',
                'type' => 'varchar',
                'collation' => null,
                'nullable' => false,
                'default' => null,
                'auto_increment' => false,
                'comment' => null,
                'generation' => null,
                'label' => 'Username',
            ],
            'created_at' => [
                'name' => 'created_at',
                'type_name' => 'datetime',
                'type' => 'datetime',
                'collation' => null,
                'nullable' => true,
                'default' => null,
                'auto_increment' => false,
                'comment' => null,
                'generation' => null,
                'label' => 'Created At',
            ],
            'updated_at' => [
                'name' => 'updated_at',
                'type_name' => 'datetime',
                'type' => 'datetime',
                'collation' => null,
                'nullable' => true,
                'default' => null,
                'auto_increment' => false,
                'comment' => null,
                'generation' => null,
                'label' => 'Updated At',
            ],
            'deleted_at' => [
                'name' => 'deleted_at',
                'type_name' => 'datetime',
                'type' => 'datetime',
                'collation' => null,
                'nullable' => true,
                'default' => null,
                'auto_increment' => false,
                'comment' => null,
                'generation' => null,
                'label' => 'Deleted At',
            ],
        ],
    ],
    'menus' => [
        'name' => 'menus',
        'comment' => null,
        'label' => 'Menu',
        'columns' => [
            'id' => [
                'name' => 'id',
                'type_name' => 'integer',
                'type' => 'integer',
                'collation' => null,
                'nullable' => false,
                'default' => null,
                'auto_increment' => true,
                'comment' => null,
                'generation' => null,
                'label' => 'Id',
            ],
            'pid' => [
                'name' => 'pid',
                'type_name' => 'integer',
                'type' => 'integer',
                'collation' => null,
                'nullable' => false,
                'default' => '\'0\'',
                'auto_increment' => false,
                'comment' => null,
                'generation' => null,
                'label' => 'Parent Id',
            ],
            'name' => [
                'name' => 'name',
                'type_name' => 'varchar',
                'type' => 'varchar',
                'collation' => null,
                'nullable' => false,
                'default' => null,
                'auto_increment' => false,
                'comment' => null,
                'generation' => null,
                'label' => 'Name',
            ],
            'path' => [
                'name' => 'path',
                'type_name' => 'varchar',
                'type' => 'varchar',
                'collation' => null,
                'nullable' => false,
                'default' => null,
                'auto_increment' => false,
                'comment' => null,
                'generation' => null,
                'label' => 'Path',
            ],
            'sort' => [
                'name' => 'sort',
                'type_name' => 'integer',
                'type' => 'integer',
                'collation' => null,
                'nullable' => false,
                'default' => null,
                'auto_increment' => false,
                'comment' => null,
                'generation' => null,
                'label' => 'Sort',
            ],
        ],
    ],
    'migrations' => [
        'name' => 'migrations',
        'comment' => null,
        'label' => 'Migration',
        'columns' => [
            'id' => [
                'name' => 'id',
                'type_name' => 'integer',
                'type' => 'integer',
                'collation' => null,
                'nullable' => false,
                'default' => null,
                'auto_increment' => true,
                'comment' => null,
                'generation' => null,
                'label' => 'Id',
            ],
            'migration' => [
                'name' => 'migration',
                'type_name' => 'varchar',
                'type' => 'varchar',
                'collation' => null,
                'nullable' => false,
                'default' => null,
                'auto_increment' => false,
                'comment' => null,
                'generation' => null,
                'label' => 'Migration',
            ],
            'batch' => [
                'name' => 'batch',
                'type_name' => 'integer',
                'type' => 'integer',
                'collation' => null,
                'nullable' => false,
                'default' => null,
                'auto_increment' => false,
                'comment' => null,
                'generation' => null,
                'label' => 'Batch',
            ],
        ],
    ],
    'operate_logs' => [
        'name' => 'operate_logs',
        'comment' => null,
        'label' => 'Operate Log',
        'columns' => [
            'id' => [
                'name' => 'id',
                'type_name' => 'integer',
                'type' => 'integer',
                'collation' => null,
                'nullable' => false,
                'default' => null,
                'auto_increment' => true,
                'comment' => null,
                'generation' => null,
                'label' => 'Id',
            ],
            'uid' => [
                'name' => 'uid',
                'type_name' => 'integer',
                'type' => 'integer',
                'collation' => null,
                'nullable' => false,
                'default' => null,
                'auto_increment' => false,
                'comment' => null,
                'generation' => null,
                'label' => 'Uid',
            ],
            'username' => [
                'name' => 'username',
                'type_name' => 'varchar',
                'type' => 'varchar',
                'collation' => null,
                'nullable' => false,
                'default' => null,
                'auto_increment' => false,
                'comment' => null,
                'generation' => null,
                'label' => 'Username',
            ],
            'user_type' => [
                'name' => 'user_type',
                'type_name' => 'varchar',
                'type' => 'varchar',
                'collation' => null,
                'nullable' => false,
                'default' => null,
                'auto_increment' => false,
                'comment' => null,
                'generation' => null,
                'label' => 'User Type',
            ],
            'action' => [
                'name' => 'action',
                'type_name' => 'varchar',
                'type' => 'varchar',
                'collation' => null,
                'nullable' => false,
                'default' => null,
                'auto_increment' => false,
                'comment' => null,
                'generation' => null,
                'label' => 'Action',
            ],
            'subject_type' => [
                'name' => 'subject_type',
                'type_name' => 'varchar',
                'type' => 'varchar',
                'collation' => null,
                'nullable' => false,
                'default' => null,
                'auto_increment' => false,
                'comment' => null,
                'generation' => null,
                'label' => 'Logging Table',
            ],
            'subject_id' => [
                'name' => 'subject_id',
                'type_name' => 'integer',
                'type' => 'integer',
                'collation' => null,
                'nullable' => false,
                'default' => null,
                'auto_increment' => false,
                'comment' => null,
                'generation' => null,
                'label' => 'Logging Id',
            ],
            'subject_name' => [
                'name' => 'subject_name',
                'type_name' => 'varchar',
                'type' => 'varchar',
                'collation' => null,
                'nullable' => false,
                'default' => null,
                'auto_increment' => false,
                'comment' => null,
                'generation' => null,
                'label' => 'Logging Name',
            ],
            'changes' => [
                'name' => 'changes',
                'type_name' => 'text',
                'type' => 'text',
                'collation' => null,
                'nullable' => true,
                'default' => null,
                'auto_increment' => false,
                'comment' => null,
                'generation' => null,
                'label' => 'Changes',
            ],
            'route' => [
                'name' => 'route',
                'type_name' => 'varchar',
                'type' => 'varchar',
                'collation' => null,
                'nullable' => false,
                'default' => null,
                'auto_increment' => false,
                'comment' => null,
                'generation' => null,
                'label' => 'Route',
            ],
            'ip' => [
                'name' => 'ip',
                'type_name' => 'varchar',
                'type' => 'varchar',
                'collation' => null,
                'nullable' => false,
                'default' => null,
                'auto_increment' => false,
                'comment' => null,
                'generation' => null,
                'label' => 'Ip',
            ],
            'created_at' => [
                'name' => 'created_at',
                'type_name' => 'datetime',
                'type' => 'datetime',
                'collation' => null,
                'nullable' => true,
                'default' => null,
                'auto_increment' => false,
                'comment' => null,
                'generation' => null,
                'label' => 'Created At',
            ],
        ],
    ],
    'sequences' => [
        'name' => 'sequences',
        'comment' => null,
        'label' => 'Sequence',
        'columns' => [
            'id' => [
                'name' => 'id',
                'type_name' => 'integer',
                'type' => 'integer',
                'collation' => null,
                'nullable' => false,
                'default' => null,
                'auto_increment' => true,
                'comment' => null,
                'generation' => null,
                'label' => 'Id',
            ],
            'name' => [
                'name' => 'name',
                'type_name' => 'varchar',
                'type' => 'varchar',
                'collation' => null,
                'nullable' => false,
                'default' => null,
                'auto_increment' => false,
                'comment' => null,
                'generation' => null,
                'label' => 'Name',
            ],
            'value' => [
                'name' => 'value',
                'type_name' => 'integer',
                'type' => 'integer',
                'collation' => null,
                'nullable' => false,
                'default' => null,
                'auto_increment' => false,
                'comment' => null,
                'generation' => null,
                'label' => 'Value',
            ],
            'created_at' => [
                'name' => 'created_at',
                'type_name' => 'datetime',
                'type' => 'datetime',
                'collation' => null,
                'nullable' => true,
                'default' => null,
                'auto_increment' => false,
                'comment' => null,
                'generation' => null,
                'label' => 'Created At',
            ],
            'updated_at' => [
                'name' => 'updated_at',
                'type_name' => 'datetime',
                'type' => 'datetime',
                'collation' => null,
                'nullable' => true,
                'default' => null,
                'auto_increment' => false,
                'comment' => null,
                'generation' => null,
                'label' => 'Updated At',
            ],
        ],
    ],
    'users' => [
        'name' => 'users',
        'comment' => null,
        'label' => '用户',
        'columns' => [
            'id' => [
                'name' => 'id',
                'type_name' => 'integer',
                'type' => 'integer',
                'collation' => null,
                'nullable' => false,
                'default' => null,
                'auto_increment' => true,
                'comment' => null,
                'generation' => null,
                'label' => 'Id',
            ],
            'username' => [
                'name' => 'username',
                'type_name' => 'varchar',
                'type' => 'varchar',
                'collation' => null,
                'nullable' => false,
                'default' => null,
                'auto_increment' => false,
                'comment' => null,
                'generation' => null,
                'label' => 'Username',
            ],
            'password' => [
                'name' => 'password',
                'type_name' => 'varchar',
                'type' => 'varchar',
                'collation' => null,
                'nullable' => false,
                'default' => '\'\'',
                'auto_increment' => false,
                'comment' => null,
                'generation' => null,
                'label' => 'Password',
            ],
            'realname' => [
                'name' => 'realname',
                'type_name' => 'varchar',
                'type' => 'varchar',
                'collation' => null,
                'nullable' => false,
                'default' => '\'\'',
                'auto_increment' => false,
                'comment' => null,
                'generation' => null,
                'label' => 'Realname',
            ],
            'created_at' => [
                'name' => 'created_at',
                'type_name' => 'datetime',
                'type' => 'datetime',
                'collation' => null,
                'nullable' => true,
                'default' => null,
                'auto_increment' => false,
                'comment' => null,
                'generation' => null,
                'label' => 'Created At',
            ],
            'updated_at' => [
                'name' => 'updated_at',
                'type_name' => 'datetime',
                'type' => 'datetime',
                'collation' => null,
                'nullable' => true,
                'default' => null,
                'auto_increment' => false,
                'comment' => null,
                'generation' => null,
                'label' => 'Updated At',
            ],
            'deleted_at' => [
                'name' => 'deleted_at',
                'type_name' => 'datetime',
                'type' => 'datetime',
                'collation' => null,
                'nullable' => true,
                'default' => null,
                'auto_increment' => false,
                'comment' => null,
                'generation' => null,
                'label' => 'Deleted At',
            ],
        ],
    ],
];
